const COMMON = "common/"
const AUTH = "auth/"
const OPTION = "option/"

export const LOGIN = AUTH + "login"
export const PROFILE = AUTH + "profile"

export const BRANCH = COMMON + "branches"
export const ROOM = COMMON + "rooms"
export const COURSE = COMMON + "courses"
export const PAYMENT_TYPE = COMMON + "payment-types"
export const PAYMENT_TYPES_OPTION = "option/payment-types"
export const HOLIDAY = COMMON + "weekends"
export const ROLE = COMMON + "roles"
export const TASKLY_PROJECT_CRM = "taskly/list-projects"
export const HR_API = "users"
export const OPTION_ROLES = OPTION + "roles"
export const OPTION_COURSES = OPTION + "courses"
export const OPTION_TEACHERS = OPTION + "teachers"
export const OPTION_ROOMS = OPTION + "rooms"
export const OPTION_GROUPS = OPTION + "groups"
export const OPTION_STUDENT = OPTION + "students"
export const EMPLOYEE = "employees"
export const SALARIES = "salary-types/attach"
export const STUDENT = "students"
export const STUDENT_GROUP = "students/groups"
export const GROUP = "platform/groups"
export const GROUP_STUDENTS = "platform/group-students"
export const GROUP_STUDENTS_PAYMENT = "platform/group-students/payments"
export const GROUP_STUDENTS_MODULES = "platform/group-students/crud/modules"

export const REFRESH_TOKEN = "token/refresh"
export const INVENTORY_CAR = `/car`
export const LOADS = `loads`
export const OFFERS = `offers`
export const OFFERS_ACCEPT = `/accept-offer`
export const OFFERS_AGENT = `/agent-offers`
export const OFFERS_FILL_AGENT = `/fill-offer-agent`
export const OFFERS_FILL = `/fill-offer`
export const OFFERS_EDIT = `/fill-edit`
export const OFFERS_SEND = `/send-offer`
export const PRODUCT = `product`
export const REGION = `region`
export const STATION = `station`
export const TRANSPORT = `transport`
export const USERS = `users`
