/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainImport } from './routes/_main'
import { Route as AuthImport } from './routes/_auth'
import { Route as MainIndexImport } from './routes/_main/index'
import { Route as FormIdImport } from './routes/form/$id'
import { Route as MainReportsImport } from './routes/_main/reports'
import { Route as MainStudentsIndexImport } from './routes/_main/students/index'
import { Route as MainLeadsIndexImport } from './routes/_main/leads/index'
import { Route as MainGroupsIndexImport } from './routes/_main/groups/index'
import { Route as MainFinanceIndexImport } from './routes/_main/finance/index'
import { Route as MainSettingsMainImport } from './routes/_main/settings/_main'
import { Route as MainLeadsSourcesImport } from './routes/_main/leads/sources'
import { Route as MainLeadsArchiveImport } from './routes/_main/leads/archive'
import { Route as MainFinanceIncomeImport } from './routes/_main/finance/income'
import { Route as MainFinanceCostImport } from './routes/_main/finance/cost'
import { Route as MainEmployeesMainImport } from './routes/_main/employees/_main'
import { Route as MainAttendanceMainImport } from './routes/_main/attendance/_main'
import { Route as MainSettingsMainIndexImport } from './routes/_main/settings/_main/index'
import { Route as MainLeadsStatsIndexImport } from './routes/_main/leads/stats/index'
import { Route as MainLeadsFormsIndexImport } from './routes/_main/leads/forms/index'
import { Route as MainLeadsIdIndexImport } from './routes/_main/leads/$id/index'
import { Route as MainEmployeesMainIndexImport } from './routes/_main/employees/_main/index'
import { Route as MainAttendanceMainIndexImport } from './routes/_main/attendance/_main/index'
import { Route as MainStudentsIdMainImport } from './routes/_main/students/$id/_main'
import { Route as MainSettingsMainRoomsImport } from './routes/_main/settings/_main/rooms'
import { Route as MainSettingsMainRolesImport } from './routes/_main/settings/_main/roles'
import { Route as MainSettingsMainPaymentTypeImport } from './routes/_main/settings/_main/payment-type'
import { Route as MainSettingsMainHolidaysImport } from './routes/_main/settings/_main/holidays'
import { Route as MainSettingsMainCoursesImport } from './routes/_main/settings/_main/courses'
import { Route as MainSettingsMainBranchesImport } from './routes/_main/settings/_main/branches'
import { Route as MainLeadsFormsCreateImport } from './routes/_main/leads/forms/create'
import { Route as MainLeadsFormsIdImport } from './routes/_main/leads/forms/$id'
import { Route as MainGroupsIdMainImport } from './routes/_main/groups/$id/_main'
import { Route as MainEmployeesMainSalaryImport } from './routes/_main/employees/_main/salary'
import { Route as MainEmployeesMainHrImport } from './routes/_main/employees/_main/hr'
import { Route as MainAttendanceMainStudentsImport } from './routes/_main/attendance/_main/students'
import { Route as MainAttendanceMainEmployeesImport } from './routes/_main/attendance/_main/employees'
import { Route as MainGroupsIdMainIndexImport } from './routes/_main/groups/$id/_main/index'
import { Route as MainStudentsIdMainSendMessageImport } from './routes/_main/students/$id/_main/send-message'
import { Route as MainStudentsIdMainPaymentsImport } from './routes/_main/students/$id/_main/payments'
import { Route as MainStudentsIdMainParentsImport } from './routes/_main/students/$id/_main/parents'
import { Route as MainStudentsIdMainNotesImport } from './routes/_main/students/$id/_main/notes'
import { Route as MainStudentsIdMainHistoryImport } from './routes/_main/students/$id/_main/history'
import { Route as MainStudentsIdMainGroupsImport } from './routes/_main/students/$id/_main/groups'
import { Route as MainStudentsIdMainDiscountImport } from './routes/_main/students/$id/_main/discount'
import { Route as MainStudentsIdMainAppropriationImport } from './routes/_main/students/$id/_main/appropriation'
import { Route as MainLeadsFormsEditIdImport } from './routes/_main/leads/forms/edit/$id'
import { Route as MainLeadsIdUserUserImport } from './routes/_main/leads/$id/user/$user'
import { Route as MainGroupsIdMainStudentsImport } from './routes/_main/groups/$id/_main/students'
import { Route as MainGroupsIdMainScoreImport } from './routes/_main/groups/$id/_main/score'
import { Route as MainGroupsIdMainSaleImport } from './routes/_main/groups/$id/_main/sale'
import { Route as MainGroupsIdMainNotesImport } from './routes/_main/groups/$id/_main/notes'
import { Route as MainGroupsIdMainAttendanceImport } from './routes/_main/groups/$id/_main/attendance'
import { Route as MainGroupsIdMainTasksIndexImport } from './routes/_main/groups/$id/_main/tasks/index'

// Create Virtual Routes

const MainSettingsImport = createFileRoute('/_main/settings')()
const MainEmployeesImport = createFileRoute('/_main/employees')()
const MainAttendanceImport = createFileRoute('/_main/attendance')()
const AuthLoginLazyImport = createFileRoute('/_auth/login')()
const MainStudentsIdImport = createFileRoute('/_main/students/$id')()
const MainGroupsIdImport = createFileRoute('/_main/groups/$id')()
const MainEmployeesMainAttendanceLazyImport = createFileRoute(
  '/_main/employees/_main/attendance',
)()

// Create/Update Routes

const MainRoute = MainImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const MainSettingsRoute = MainSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRoute,
} as any)

const MainEmployeesRoute = MainEmployeesImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => MainRoute,
} as any)

const MainAttendanceRoute = MainAttendanceImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => MainRoute,
} as any)

const MainIndexRoute = MainIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)

const AuthLoginLazyRoute = AuthLoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/login.lazy').then((d) => d.Route))

const FormIdRoute = FormIdImport.update({
  id: '/form/$id',
  path: '/form/$id',
  getParentRoute: () => rootRoute,
} as any)

const MainReportsRoute = MainReportsImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => MainRoute,
} as any)

const MainStudentsIdRoute = MainStudentsIdImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => MainRoute,
} as any)

const MainGroupsIdRoute = MainGroupsIdImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => MainRoute,
} as any)

const MainStudentsIndexRoute = MainStudentsIndexImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => MainRoute,
} as any)

const MainLeadsIndexRoute = MainLeadsIndexImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => MainRoute,
} as any)

const MainGroupsIndexRoute = MainGroupsIndexImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => MainRoute,
} as any)

const MainFinanceIndexRoute = MainFinanceIndexImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => MainRoute,
} as any)

const MainSettingsMainRoute = MainSettingsMainImport.update({
  id: '/_main',
  getParentRoute: () => MainSettingsRoute,
} as any)

const MainLeadsSourcesRoute = MainLeadsSourcesImport.update({
  id: '/leads/sources',
  path: '/leads/sources',
  getParentRoute: () => MainRoute,
} as any)

const MainLeadsArchiveRoute = MainLeadsArchiveImport.update({
  id: '/leads/archive',
  path: '/leads/archive',
  getParentRoute: () => MainRoute,
} as any)

const MainFinanceIncomeRoute = MainFinanceIncomeImport.update({
  id: '/finance/income',
  path: '/finance/income',
  getParentRoute: () => MainRoute,
} as any)

const MainFinanceCostRoute = MainFinanceCostImport.update({
  id: '/finance/cost',
  path: '/finance/cost',
  getParentRoute: () => MainRoute,
} as any)

const MainEmployeesMainRoute = MainEmployeesMainImport.update({
  id: '/_main',
  getParentRoute: () => MainEmployeesRoute,
} as any)

const MainAttendanceMainRoute = MainAttendanceMainImport.update({
  id: '/_main',
  getParentRoute: () => MainAttendanceRoute,
} as any)

const MainSettingsMainIndexRoute = MainSettingsMainIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainSettingsMainRoute,
} as any)

const MainLeadsStatsIndexRoute = MainLeadsStatsIndexImport.update({
  id: '/leads/stats/',
  path: '/leads/stats/',
  getParentRoute: () => MainRoute,
} as any)

const MainLeadsFormsIndexRoute = MainLeadsFormsIndexImport.update({
  id: '/leads/forms/',
  path: '/leads/forms/',
  getParentRoute: () => MainRoute,
} as any)

const MainLeadsIdIndexRoute = MainLeadsIdIndexImport.update({
  id: '/leads/$id/',
  path: '/leads/$id/',
  getParentRoute: () => MainRoute,
} as any)

const MainEmployeesMainIndexRoute = MainEmployeesMainIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainEmployeesMainRoute,
} as any)

const MainAttendanceMainIndexRoute = MainAttendanceMainIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainAttendanceMainRoute,
} as any)

const MainEmployeesMainAttendanceLazyRoute =
  MainEmployeesMainAttendanceLazyImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => MainEmployeesMainRoute,
  } as any).lazy(() =>
    import('./routes/_main/employees/_main/attendance.lazy').then(
      (d) => d.Route,
    ),
  )

const MainStudentsIdMainRoute = MainStudentsIdMainImport.update({
  id: '/_main',
  getParentRoute: () => MainStudentsIdRoute,
} as any)

const MainSettingsMainRoomsRoute = MainSettingsMainRoomsImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => MainSettingsMainRoute,
} as any)

const MainSettingsMainRolesRoute = MainSettingsMainRolesImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => MainSettingsMainRoute,
} as any)

const MainSettingsMainPaymentTypeRoute =
  MainSettingsMainPaymentTypeImport.update({
    id: '/payment-type',
    path: '/payment-type',
    getParentRoute: () => MainSettingsMainRoute,
  } as any)

const MainSettingsMainHolidaysRoute = MainSettingsMainHolidaysImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => MainSettingsMainRoute,
} as any)

const MainSettingsMainCoursesRoute = MainSettingsMainCoursesImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => MainSettingsMainRoute,
} as any)

const MainSettingsMainBranchesRoute = MainSettingsMainBranchesImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => MainSettingsMainRoute,
} as any)

const MainLeadsFormsCreateRoute = MainLeadsFormsCreateImport.update({
  id: '/leads/forms/create',
  path: '/leads/forms/create',
  getParentRoute: () => MainRoute,
} as any)

const MainLeadsFormsIdRoute = MainLeadsFormsIdImport.update({
  id: '/leads/forms/$id',
  path: '/leads/forms/$id',
  getParentRoute: () => MainRoute,
} as any)

const MainGroupsIdMainRoute = MainGroupsIdMainImport.update({
  id: '/_main',
  getParentRoute: () => MainGroupsIdRoute,
} as any)

const MainEmployeesMainSalaryRoute = MainEmployeesMainSalaryImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => MainEmployeesMainRoute,
} as any)

const MainEmployeesMainHrRoute = MainEmployeesMainHrImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => MainEmployeesMainRoute,
} as any)

const MainAttendanceMainStudentsRoute = MainAttendanceMainStudentsImport.update(
  {
    id: '/students',
    path: '/students',
    getParentRoute: () => MainAttendanceMainRoute,
  } as any,
)

const MainAttendanceMainEmployeesRoute =
  MainAttendanceMainEmployeesImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => MainAttendanceMainRoute,
  } as any)

const MainGroupsIdMainIndexRoute = MainGroupsIdMainIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainGroupsIdMainRoute,
} as any)

const MainStudentsIdMainSendMessageRoute =
  MainStudentsIdMainSendMessageImport.update({
    id: '/send-message',
    path: '/send-message',
    getParentRoute: () => MainStudentsIdMainRoute,
  } as any)

const MainStudentsIdMainPaymentsRoute = MainStudentsIdMainPaymentsImport.update(
  {
    id: '/payments',
    path: '/payments',
    getParentRoute: () => MainStudentsIdMainRoute,
  } as any,
)

const MainStudentsIdMainParentsRoute = MainStudentsIdMainParentsImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => MainStudentsIdMainRoute,
} as any)

const MainStudentsIdMainNotesRoute = MainStudentsIdMainNotesImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => MainStudentsIdMainRoute,
} as any)

const MainStudentsIdMainHistoryRoute = MainStudentsIdMainHistoryImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => MainStudentsIdMainRoute,
} as any)

const MainStudentsIdMainGroupsRoute = MainStudentsIdMainGroupsImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => MainStudentsIdMainRoute,
} as any)

const MainStudentsIdMainDiscountRoute = MainStudentsIdMainDiscountImport.update(
  {
    id: '/discount',
    path: '/discount',
    getParentRoute: () => MainStudentsIdMainRoute,
  } as any,
)

const MainStudentsIdMainAppropriationRoute =
  MainStudentsIdMainAppropriationImport.update({
    id: '/appropriation',
    path: '/appropriation',
    getParentRoute: () => MainStudentsIdMainRoute,
  } as any)

const MainLeadsFormsEditIdRoute = MainLeadsFormsEditIdImport.update({
  id: '/leads/forms/edit/$id',
  path: '/leads/forms/edit/$id',
  getParentRoute: () => MainRoute,
} as any)

const MainLeadsIdUserUserRoute = MainLeadsIdUserUserImport.update({
  id: '/leads/$id/user/$user',
  path: '/leads/$id/user/$user',
  getParentRoute: () => MainRoute,
} as any)

const MainGroupsIdMainStudentsRoute = MainGroupsIdMainStudentsImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => MainGroupsIdMainRoute,
} as any)

const MainGroupsIdMainScoreRoute = MainGroupsIdMainScoreImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => MainGroupsIdMainRoute,
} as any)

const MainGroupsIdMainSaleRoute = MainGroupsIdMainSaleImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => MainGroupsIdMainRoute,
} as any)

const MainGroupsIdMainNotesRoute = MainGroupsIdMainNotesImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => MainGroupsIdMainRoute,
} as any)

const MainGroupsIdMainAttendanceRoute = MainGroupsIdMainAttendanceImport.update(
  {
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => MainGroupsIdMainRoute,
  } as any,
)

const MainGroupsIdMainTasksIndexRoute = MainGroupsIdMainTasksIndexImport.update(
  {
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => MainGroupsIdMainRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/_main/reports': {
      id: '/_main/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof MainReportsImport
      parentRoute: typeof MainImport
    }
    '/form/$id': {
      id: '/form/$id'
      path: '/form/$id'
      fullPath: '/form/$id'
      preLoaderRoute: typeof FormIdImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginLazyImport
      parentRoute: typeof AuthImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/attendance': {
      id: '/_main/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof MainAttendanceImport
      parentRoute: typeof MainImport
    }
    '/_main/attendance/_main': {
      id: '/_main/attendance/_main'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof MainAttendanceMainImport
      parentRoute: typeof MainAttendanceRoute
    }
    '/_main/employees': {
      id: '/_main/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof MainEmployeesImport
      parentRoute: typeof MainImport
    }
    '/_main/employees/_main': {
      id: '/_main/employees/_main'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof MainEmployeesMainImport
      parentRoute: typeof MainEmployeesRoute
    }
    '/_main/finance/cost': {
      id: '/_main/finance/cost'
      path: '/finance/cost'
      fullPath: '/finance/cost'
      preLoaderRoute: typeof MainFinanceCostImport
      parentRoute: typeof MainImport
    }
    '/_main/finance/income': {
      id: '/_main/finance/income'
      path: '/finance/income'
      fullPath: '/finance/income'
      preLoaderRoute: typeof MainFinanceIncomeImport
      parentRoute: typeof MainImport
    }
    '/_main/leads/archive': {
      id: '/_main/leads/archive'
      path: '/leads/archive'
      fullPath: '/leads/archive'
      preLoaderRoute: typeof MainLeadsArchiveImport
      parentRoute: typeof MainImport
    }
    '/_main/leads/sources': {
      id: '/_main/leads/sources'
      path: '/leads/sources'
      fullPath: '/leads/sources'
      preLoaderRoute: typeof MainLeadsSourcesImport
      parentRoute: typeof MainImport
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsImport
      parentRoute: typeof MainImport
    }
    '/_main/settings/_main': {
      id: '/_main/settings/_main'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsMainImport
      parentRoute: typeof MainSettingsRoute
    }
    '/_main/finance/': {
      id: '/_main/finance/'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof MainFinanceIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/groups/': {
      id: '/_main/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof MainGroupsIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/leads/': {
      id: '/_main/leads/'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof MainLeadsIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/students/': {
      id: '/_main/students/'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof MainStudentsIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/attendance/_main/employees': {
      id: '/_main/attendance/_main/employees'
      path: '/employees'
      fullPath: '/attendance/employees'
      preLoaderRoute: typeof MainAttendanceMainEmployeesImport
      parentRoute: typeof MainAttendanceMainImport
    }
    '/_main/attendance/_main/students': {
      id: '/_main/attendance/_main/students'
      path: '/students'
      fullPath: '/attendance/students'
      preLoaderRoute: typeof MainAttendanceMainStudentsImport
      parentRoute: typeof MainAttendanceMainImport
    }
    '/_main/employees/_main/hr': {
      id: '/_main/employees/_main/hr'
      path: '/hr'
      fullPath: '/employees/hr'
      preLoaderRoute: typeof MainEmployeesMainHrImport
      parentRoute: typeof MainEmployeesMainImport
    }
    '/_main/employees/_main/salary': {
      id: '/_main/employees/_main/salary'
      path: '/salary'
      fullPath: '/employees/salary'
      preLoaderRoute: typeof MainEmployeesMainSalaryImport
      parentRoute: typeof MainEmployeesMainImport
    }
    '/_main/groups/$id': {
      id: '/_main/groups/$id'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof MainGroupsIdImport
      parentRoute: typeof MainImport
    }
    '/_main/groups/$id/_main': {
      id: '/_main/groups/$id/_main'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof MainGroupsIdMainImport
      parentRoute: typeof MainGroupsIdRoute
    }
    '/_main/leads/forms/$id': {
      id: '/_main/leads/forms/$id'
      path: '/leads/forms/$id'
      fullPath: '/leads/forms/$id'
      preLoaderRoute: typeof MainLeadsFormsIdImport
      parentRoute: typeof MainImport
    }
    '/_main/leads/forms/create': {
      id: '/_main/leads/forms/create'
      path: '/leads/forms/create'
      fullPath: '/leads/forms/create'
      preLoaderRoute: typeof MainLeadsFormsCreateImport
      parentRoute: typeof MainImport
    }
    '/_main/settings/_main/branches': {
      id: '/_main/settings/_main/branches'
      path: '/branches'
      fullPath: '/settings/branches'
      preLoaderRoute: typeof MainSettingsMainBranchesImport
      parentRoute: typeof MainSettingsMainImport
    }
    '/_main/settings/_main/courses': {
      id: '/_main/settings/_main/courses'
      path: '/courses'
      fullPath: '/settings/courses'
      preLoaderRoute: typeof MainSettingsMainCoursesImport
      parentRoute: typeof MainSettingsMainImport
    }
    '/_main/settings/_main/holidays': {
      id: '/_main/settings/_main/holidays'
      path: '/holidays'
      fullPath: '/settings/holidays'
      preLoaderRoute: typeof MainSettingsMainHolidaysImport
      parentRoute: typeof MainSettingsMainImport
    }
    '/_main/settings/_main/payment-type': {
      id: '/_main/settings/_main/payment-type'
      path: '/payment-type'
      fullPath: '/settings/payment-type'
      preLoaderRoute: typeof MainSettingsMainPaymentTypeImport
      parentRoute: typeof MainSettingsMainImport
    }
    '/_main/settings/_main/roles': {
      id: '/_main/settings/_main/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof MainSettingsMainRolesImport
      parentRoute: typeof MainSettingsMainImport
    }
    '/_main/settings/_main/rooms': {
      id: '/_main/settings/_main/rooms'
      path: '/rooms'
      fullPath: '/settings/rooms'
      preLoaderRoute: typeof MainSettingsMainRoomsImport
      parentRoute: typeof MainSettingsMainImport
    }
    '/_main/students/$id': {
      id: '/_main/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof MainStudentsIdImport
      parentRoute: typeof MainImport
    }
    '/_main/students/$id/_main': {
      id: '/_main/students/$id/_main'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof MainStudentsIdMainImport
      parentRoute: typeof MainStudentsIdRoute
    }
    '/_main/employees/_main/attendance': {
      id: '/_main/employees/_main/attendance'
      path: '/attendance'
      fullPath: '/employees/attendance'
      preLoaderRoute: typeof MainEmployeesMainAttendanceLazyImport
      parentRoute: typeof MainEmployeesMainImport
    }
    '/_main/attendance/_main/': {
      id: '/_main/attendance/_main/'
      path: '/'
      fullPath: '/attendance/'
      preLoaderRoute: typeof MainAttendanceMainIndexImport
      parentRoute: typeof MainAttendanceMainImport
    }
    '/_main/employees/_main/': {
      id: '/_main/employees/_main/'
      path: '/'
      fullPath: '/employees/'
      preLoaderRoute: typeof MainEmployeesMainIndexImport
      parentRoute: typeof MainEmployeesMainImport
    }
    '/_main/leads/$id/': {
      id: '/_main/leads/$id/'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof MainLeadsIdIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/leads/forms/': {
      id: '/_main/leads/forms/'
      path: '/leads/forms'
      fullPath: '/leads/forms'
      preLoaderRoute: typeof MainLeadsFormsIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/leads/stats/': {
      id: '/_main/leads/stats/'
      path: '/leads/stats'
      fullPath: '/leads/stats'
      preLoaderRoute: typeof MainLeadsStatsIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/settings/_main/': {
      id: '/_main/settings/_main/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof MainSettingsMainIndexImport
      parentRoute: typeof MainSettingsMainImport
    }
    '/_main/groups/$id/_main/attendance': {
      id: '/_main/groups/$id/_main/attendance'
      path: '/attendance'
      fullPath: '/groups/$id/attendance'
      preLoaderRoute: typeof MainGroupsIdMainAttendanceImport
      parentRoute: typeof MainGroupsIdMainImport
    }
    '/_main/groups/$id/_main/notes': {
      id: '/_main/groups/$id/_main/notes'
      path: '/notes'
      fullPath: '/groups/$id/notes'
      preLoaderRoute: typeof MainGroupsIdMainNotesImport
      parentRoute: typeof MainGroupsIdMainImport
    }
    '/_main/groups/$id/_main/sale': {
      id: '/_main/groups/$id/_main/sale'
      path: '/sale'
      fullPath: '/groups/$id/sale'
      preLoaderRoute: typeof MainGroupsIdMainSaleImport
      parentRoute: typeof MainGroupsIdMainImport
    }
    '/_main/groups/$id/_main/score': {
      id: '/_main/groups/$id/_main/score'
      path: '/score'
      fullPath: '/groups/$id/score'
      preLoaderRoute: typeof MainGroupsIdMainScoreImport
      parentRoute: typeof MainGroupsIdMainImport
    }
    '/_main/groups/$id/_main/students': {
      id: '/_main/groups/$id/_main/students'
      path: '/students'
      fullPath: '/groups/$id/students'
      preLoaderRoute: typeof MainGroupsIdMainStudentsImport
      parentRoute: typeof MainGroupsIdMainImport
    }
    '/_main/leads/$id/user/$user': {
      id: '/_main/leads/$id/user/$user'
      path: '/leads/$id/user/$user'
      fullPath: '/leads/$id/user/$user'
      preLoaderRoute: typeof MainLeadsIdUserUserImport
      parentRoute: typeof MainImport
    }
    '/_main/leads/forms/edit/$id': {
      id: '/_main/leads/forms/edit/$id'
      path: '/leads/forms/edit/$id'
      fullPath: '/leads/forms/edit/$id'
      preLoaderRoute: typeof MainLeadsFormsEditIdImport
      parentRoute: typeof MainImport
    }
    '/_main/students/$id/_main/appropriation': {
      id: '/_main/students/$id/_main/appropriation'
      path: '/appropriation'
      fullPath: '/students/$id/appropriation'
      preLoaderRoute: typeof MainStudentsIdMainAppropriationImport
      parentRoute: typeof MainStudentsIdMainImport
    }
    '/_main/students/$id/_main/discount': {
      id: '/_main/students/$id/_main/discount'
      path: '/discount'
      fullPath: '/students/$id/discount'
      preLoaderRoute: typeof MainStudentsIdMainDiscountImport
      parentRoute: typeof MainStudentsIdMainImport
    }
    '/_main/students/$id/_main/groups': {
      id: '/_main/students/$id/_main/groups'
      path: '/groups'
      fullPath: '/students/$id/groups'
      preLoaderRoute: typeof MainStudentsIdMainGroupsImport
      parentRoute: typeof MainStudentsIdMainImport
    }
    '/_main/students/$id/_main/history': {
      id: '/_main/students/$id/_main/history'
      path: '/history'
      fullPath: '/students/$id/history'
      preLoaderRoute: typeof MainStudentsIdMainHistoryImport
      parentRoute: typeof MainStudentsIdMainImport
    }
    '/_main/students/$id/_main/notes': {
      id: '/_main/students/$id/_main/notes'
      path: '/notes'
      fullPath: '/students/$id/notes'
      preLoaderRoute: typeof MainStudentsIdMainNotesImport
      parentRoute: typeof MainStudentsIdMainImport
    }
    '/_main/students/$id/_main/parents': {
      id: '/_main/students/$id/_main/parents'
      path: '/parents'
      fullPath: '/students/$id/parents'
      preLoaderRoute: typeof MainStudentsIdMainParentsImport
      parentRoute: typeof MainStudentsIdMainImport
    }
    '/_main/students/$id/_main/payments': {
      id: '/_main/students/$id/_main/payments'
      path: '/payments'
      fullPath: '/students/$id/payments'
      preLoaderRoute: typeof MainStudentsIdMainPaymentsImport
      parentRoute: typeof MainStudentsIdMainImport
    }
    '/_main/students/$id/_main/send-message': {
      id: '/_main/students/$id/_main/send-message'
      path: '/send-message'
      fullPath: '/students/$id/send-message'
      preLoaderRoute: typeof MainStudentsIdMainSendMessageImport
      parentRoute: typeof MainStudentsIdMainImport
    }
    '/_main/groups/$id/_main/': {
      id: '/_main/groups/$id/_main/'
      path: '/'
      fullPath: '/groups/$id/'
      preLoaderRoute: typeof MainGroupsIdMainIndexImport
      parentRoute: typeof MainGroupsIdMainImport
    }
    '/_main/groups/$id/_main/tasks/': {
      id: '/_main/groups/$id/_main/tasks/'
      path: '/tasks'
      fullPath: '/groups/$id/tasks'
      preLoaderRoute: typeof MainGroupsIdMainTasksIndexImport
      parentRoute: typeof MainGroupsIdMainImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthLoginLazyRoute: typeof AuthLoginLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginLazyRoute: AuthLoginLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainAttendanceMainRouteChildren {
  MainAttendanceMainEmployeesRoute: typeof MainAttendanceMainEmployeesRoute
  MainAttendanceMainStudentsRoute: typeof MainAttendanceMainStudentsRoute
  MainAttendanceMainIndexRoute: typeof MainAttendanceMainIndexRoute
}

const MainAttendanceMainRouteChildren: MainAttendanceMainRouteChildren = {
  MainAttendanceMainEmployeesRoute: MainAttendanceMainEmployeesRoute,
  MainAttendanceMainStudentsRoute: MainAttendanceMainStudentsRoute,
  MainAttendanceMainIndexRoute: MainAttendanceMainIndexRoute,
}

const MainAttendanceMainRouteWithChildren =
  MainAttendanceMainRoute._addFileChildren(MainAttendanceMainRouteChildren)

interface MainAttendanceRouteChildren {
  MainAttendanceMainRoute: typeof MainAttendanceMainRouteWithChildren
}

const MainAttendanceRouteChildren: MainAttendanceRouteChildren = {
  MainAttendanceMainRoute: MainAttendanceMainRouteWithChildren,
}

const MainAttendanceRouteWithChildren = MainAttendanceRoute._addFileChildren(
  MainAttendanceRouteChildren,
)

interface MainEmployeesMainRouteChildren {
  MainEmployeesMainHrRoute: typeof MainEmployeesMainHrRoute
  MainEmployeesMainSalaryRoute: typeof MainEmployeesMainSalaryRoute
  MainEmployeesMainAttendanceLazyRoute: typeof MainEmployeesMainAttendanceLazyRoute
  MainEmployeesMainIndexRoute: typeof MainEmployeesMainIndexRoute
}

const MainEmployeesMainRouteChildren: MainEmployeesMainRouteChildren = {
  MainEmployeesMainHrRoute: MainEmployeesMainHrRoute,
  MainEmployeesMainSalaryRoute: MainEmployeesMainSalaryRoute,
  MainEmployeesMainAttendanceLazyRoute: MainEmployeesMainAttendanceLazyRoute,
  MainEmployeesMainIndexRoute: MainEmployeesMainIndexRoute,
}

const MainEmployeesMainRouteWithChildren =
  MainEmployeesMainRoute._addFileChildren(MainEmployeesMainRouteChildren)

interface MainEmployeesRouteChildren {
  MainEmployeesMainRoute: typeof MainEmployeesMainRouteWithChildren
}

const MainEmployeesRouteChildren: MainEmployeesRouteChildren = {
  MainEmployeesMainRoute: MainEmployeesMainRouteWithChildren,
}

const MainEmployeesRouteWithChildren = MainEmployeesRoute._addFileChildren(
  MainEmployeesRouteChildren,
)

interface MainSettingsMainRouteChildren {
  MainSettingsMainBranchesRoute: typeof MainSettingsMainBranchesRoute
  MainSettingsMainCoursesRoute: typeof MainSettingsMainCoursesRoute
  MainSettingsMainHolidaysRoute: typeof MainSettingsMainHolidaysRoute
  MainSettingsMainPaymentTypeRoute: typeof MainSettingsMainPaymentTypeRoute
  MainSettingsMainRolesRoute: typeof MainSettingsMainRolesRoute
  MainSettingsMainRoomsRoute: typeof MainSettingsMainRoomsRoute
  MainSettingsMainIndexRoute: typeof MainSettingsMainIndexRoute
}

const MainSettingsMainRouteChildren: MainSettingsMainRouteChildren = {
  MainSettingsMainBranchesRoute: MainSettingsMainBranchesRoute,
  MainSettingsMainCoursesRoute: MainSettingsMainCoursesRoute,
  MainSettingsMainHolidaysRoute: MainSettingsMainHolidaysRoute,
  MainSettingsMainPaymentTypeRoute: MainSettingsMainPaymentTypeRoute,
  MainSettingsMainRolesRoute: MainSettingsMainRolesRoute,
  MainSettingsMainRoomsRoute: MainSettingsMainRoomsRoute,
  MainSettingsMainIndexRoute: MainSettingsMainIndexRoute,
}

const MainSettingsMainRouteWithChildren =
  MainSettingsMainRoute._addFileChildren(MainSettingsMainRouteChildren)

interface MainSettingsRouteChildren {
  MainSettingsMainRoute: typeof MainSettingsMainRouteWithChildren
}

const MainSettingsRouteChildren: MainSettingsRouteChildren = {
  MainSettingsMainRoute: MainSettingsMainRouteWithChildren,
}

const MainSettingsRouteWithChildren = MainSettingsRoute._addFileChildren(
  MainSettingsRouteChildren,
)

interface MainGroupsIdMainRouteChildren {
  MainGroupsIdMainAttendanceRoute: typeof MainGroupsIdMainAttendanceRoute
  MainGroupsIdMainNotesRoute: typeof MainGroupsIdMainNotesRoute
  MainGroupsIdMainSaleRoute: typeof MainGroupsIdMainSaleRoute
  MainGroupsIdMainScoreRoute: typeof MainGroupsIdMainScoreRoute
  MainGroupsIdMainStudentsRoute: typeof MainGroupsIdMainStudentsRoute
  MainGroupsIdMainIndexRoute: typeof MainGroupsIdMainIndexRoute
  MainGroupsIdMainTasksIndexRoute: typeof MainGroupsIdMainTasksIndexRoute
}

const MainGroupsIdMainRouteChildren: MainGroupsIdMainRouteChildren = {
  MainGroupsIdMainAttendanceRoute: MainGroupsIdMainAttendanceRoute,
  MainGroupsIdMainNotesRoute: MainGroupsIdMainNotesRoute,
  MainGroupsIdMainSaleRoute: MainGroupsIdMainSaleRoute,
  MainGroupsIdMainScoreRoute: MainGroupsIdMainScoreRoute,
  MainGroupsIdMainStudentsRoute: MainGroupsIdMainStudentsRoute,
  MainGroupsIdMainIndexRoute: MainGroupsIdMainIndexRoute,
  MainGroupsIdMainTasksIndexRoute: MainGroupsIdMainTasksIndexRoute,
}

const MainGroupsIdMainRouteWithChildren =
  MainGroupsIdMainRoute._addFileChildren(MainGroupsIdMainRouteChildren)

interface MainGroupsIdRouteChildren {
  MainGroupsIdMainRoute: typeof MainGroupsIdMainRouteWithChildren
}

const MainGroupsIdRouteChildren: MainGroupsIdRouteChildren = {
  MainGroupsIdMainRoute: MainGroupsIdMainRouteWithChildren,
}

const MainGroupsIdRouteWithChildren = MainGroupsIdRoute._addFileChildren(
  MainGroupsIdRouteChildren,
)

interface MainStudentsIdMainRouteChildren {
  MainStudentsIdMainAppropriationRoute: typeof MainStudentsIdMainAppropriationRoute
  MainStudentsIdMainDiscountRoute: typeof MainStudentsIdMainDiscountRoute
  MainStudentsIdMainGroupsRoute: typeof MainStudentsIdMainGroupsRoute
  MainStudentsIdMainHistoryRoute: typeof MainStudentsIdMainHistoryRoute
  MainStudentsIdMainNotesRoute: typeof MainStudentsIdMainNotesRoute
  MainStudentsIdMainParentsRoute: typeof MainStudentsIdMainParentsRoute
  MainStudentsIdMainPaymentsRoute: typeof MainStudentsIdMainPaymentsRoute
  MainStudentsIdMainSendMessageRoute: typeof MainStudentsIdMainSendMessageRoute
}

const MainStudentsIdMainRouteChildren: MainStudentsIdMainRouteChildren = {
  MainStudentsIdMainAppropriationRoute: MainStudentsIdMainAppropriationRoute,
  MainStudentsIdMainDiscountRoute: MainStudentsIdMainDiscountRoute,
  MainStudentsIdMainGroupsRoute: MainStudentsIdMainGroupsRoute,
  MainStudentsIdMainHistoryRoute: MainStudentsIdMainHistoryRoute,
  MainStudentsIdMainNotesRoute: MainStudentsIdMainNotesRoute,
  MainStudentsIdMainParentsRoute: MainStudentsIdMainParentsRoute,
  MainStudentsIdMainPaymentsRoute: MainStudentsIdMainPaymentsRoute,
  MainStudentsIdMainSendMessageRoute: MainStudentsIdMainSendMessageRoute,
}

const MainStudentsIdMainRouteWithChildren =
  MainStudentsIdMainRoute._addFileChildren(MainStudentsIdMainRouteChildren)

interface MainStudentsIdRouteChildren {
  MainStudentsIdMainRoute: typeof MainStudentsIdMainRouteWithChildren
}

const MainStudentsIdRouteChildren: MainStudentsIdRouteChildren = {
  MainStudentsIdMainRoute: MainStudentsIdMainRouteWithChildren,
}

const MainStudentsIdRouteWithChildren = MainStudentsIdRoute._addFileChildren(
  MainStudentsIdRouteChildren,
)

interface MainRouteChildren {
  MainReportsRoute: typeof MainReportsRoute
  MainIndexRoute: typeof MainIndexRoute
  MainAttendanceRoute: typeof MainAttendanceRouteWithChildren
  MainEmployeesRoute: typeof MainEmployeesRouteWithChildren
  MainFinanceCostRoute: typeof MainFinanceCostRoute
  MainFinanceIncomeRoute: typeof MainFinanceIncomeRoute
  MainLeadsArchiveRoute: typeof MainLeadsArchiveRoute
  MainLeadsSourcesRoute: typeof MainLeadsSourcesRoute
  MainSettingsRoute: typeof MainSettingsRouteWithChildren
  MainFinanceIndexRoute: typeof MainFinanceIndexRoute
  MainGroupsIndexRoute: typeof MainGroupsIndexRoute
  MainLeadsIndexRoute: typeof MainLeadsIndexRoute
  MainStudentsIndexRoute: typeof MainStudentsIndexRoute
  MainGroupsIdRoute: typeof MainGroupsIdRouteWithChildren
  MainLeadsFormsIdRoute: typeof MainLeadsFormsIdRoute
  MainLeadsFormsCreateRoute: typeof MainLeadsFormsCreateRoute
  MainStudentsIdRoute: typeof MainStudentsIdRouteWithChildren
  MainLeadsIdIndexRoute: typeof MainLeadsIdIndexRoute
  MainLeadsFormsIndexRoute: typeof MainLeadsFormsIndexRoute
  MainLeadsStatsIndexRoute: typeof MainLeadsStatsIndexRoute
  MainLeadsIdUserUserRoute: typeof MainLeadsIdUserUserRoute
  MainLeadsFormsEditIdRoute: typeof MainLeadsFormsEditIdRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainReportsRoute: MainReportsRoute,
  MainIndexRoute: MainIndexRoute,
  MainAttendanceRoute: MainAttendanceRouteWithChildren,
  MainEmployeesRoute: MainEmployeesRouteWithChildren,
  MainFinanceCostRoute: MainFinanceCostRoute,
  MainFinanceIncomeRoute: MainFinanceIncomeRoute,
  MainLeadsArchiveRoute: MainLeadsArchiveRoute,
  MainLeadsSourcesRoute: MainLeadsSourcesRoute,
  MainSettingsRoute: MainSettingsRouteWithChildren,
  MainFinanceIndexRoute: MainFinanceIndexRoute,
  MainGroupsIndexRoute: MainGroupsIndexRoute,
  MainLeadsIndexRoute: MainLeadsIndexRoute,
  MainStudentsIndexRoute: MainStudentsIndexRoute,
  MainGroupsIdRoute: MainGroupsIdRouteWithChildren,
  MainLeadsFormsIdRoute: MainLeadsFormsIdRoute,
  MainLeadsFormsCreateRoute: MainLeadsFormsCreateRoute,
  MainStudentsIdRoute: MainStudentsIdRouteWithChildren,
  MainLeadsIdIndexRoute: MainLeadsIdIndexRoute,
  MainLeadsFormsIndexRoute: MainLeadsFormsIndexRoute,
  MainLeadsStatsIndexRoute: MainLeadsStatsIndexRoute,
  MainLeadsIdUserUserRoute: MainLeadsIdUserUserRoute,
  MainLeadsFormsEditIdRoute: MainLeadsFormsEditIdRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof MainRouteWithChildren
  '/reports': typeof MainReportsRoute
  '/form/$id': typeof FormIdRoute
  '/login': typeof AuthLoginLazyRoute
  '/': typeof MainIndexRoute
  '/attendance': typeof MainAttendanceMainRouteWithChildren
  '/employees': typeof MainEmployeesMainRouteWithChildren
  '/finance/cost': typeof MainFinanceCostRoute
  '/finance/income': typeof MainFinanceIncomeRoute
  '/leads/archive': typeof MainLeadsArchiveRoute
  '/leads/sources': typeof MainLeadsSourcesRoute
  '/settings': typeof MainSettingsMainRouteWithChildren
  '/finance': typeof MainFinanceIndexRoute
  '/groups': typeof MainGroupsIndexRoute
  '/leads': typeof MainLeadsIndexRoute
  '/students': typeof MainStudentsIndexRoute
  '/attendance/employees': typeof MainAttendanceMainEmployeesRoute
  '/attendance/students': typeof MainAttendanceMainStudentsRoute
  '/employees/hr': typeof MainEmployeesMainHrRoute
  '/employees/salary': typeof MainEmployeesMainSalaryRoute
  '/groups/$id': typeof MainGroupsIdMainRouteWithChildren
  '/leads/forms/$id': typeof MainLeadsFormsIdRoute
  '/leads/forms/create': typeof MainLeadsFormsCreateRoute
  '/settings/branches': typeof MainSettingsMainBranchesRoute
  '/settings/courses': typeof MainSettingsMainCoursesRoute
  '/settings/holidays': typeof MainSettingsMainHolidaysRoute
  '/settings/payment-type': typeof MainSettingsMainPaymentTypeRoute
  '/settings/roles': typeof MainSettingsMainRolesRoute
  '/settings/rooms': typeof MainSettingsMainRoomsRoute
  '/students/$id': typeof MainStudentsIdMainRouteWithChildren
  '/employees/attendance': typeof MainEmployeesMainAttendanceLazyRoute
  '/attendance/': typeof MainAttendanceMainIndexRoute
  '/employees/': typeof MainEmployeesMainIndexRoute
  '/leads/$id': typeof MainLeadsIdIndexRoute
  '/leads/forms': typeof MainLeadsFormsIndexRoute
  '/leads/stats': typeof MainLeadsStatsIndexRoute
  '/settings/': typeof MainSettingsMainIndexRoute
  '/groups/$id/attendance': typeof MainGroupsIdMainAttendanceRoute
  '/groups/$id/notes': typeof MainGroupsIdMainNotesRoute
  '/groups/$id/sale': typeof MainGroupsIdMainSaleRoute
  '/groups/$id/score': typeof MainGroupsIdMainScoreRoute
  '/groups/$id/students': typeof MainGroupsIdMainStudentsRoute
  '/leads/$id/user/$user': typeof MainLeadsIdUserUserRoute
  '/leads/forms/edit/$id': typeof MainLeadsFormsEditIdRoute
  '/students/$id/appropriation': typeof MainStudentsIdMainAppropriationRoute
  '/students/$id/discount': typeof MainStudentsIdMainDiscountRoute
  '/students/$id/groups': typeof MainStudentsIdMainGroupsRoute
  '/students/$id/history': typeof MainStudentsIdMainHistoryRoute
  '/students/$id/notes': typeof MainStudentsIdMainNotesRoute
  '/students/$id/parents': typeof MainStudentsIdMainParentsRoute
  '/students/$id/payments': typeof MainStudentsIdMainPaymentsRoute
  '/students/$id/send-message': typeof MainStudentsIdMainSendMessageRoute
  '/groups/$id/': typeof MainGroupsIdMainIndexRoute
  '/groups/$id/tasks': typeof MainGroupsIdMainTasksIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthRouteWithChildren
  '/reports': typeof MainReportsRoute
  '/form/$id': typeof FormIdRoute
  '/login': typeof AuthLoginLazyRoute
  '/': typeof MainIndexRoute
  '/attendance': typeof MainAttendanceMainIndexRoute
  '/employees': typeof MainEmployeesMainIndexRoute
  '/finance/cost': typeof MainFinanceCostRoute
  '/finance/income': typeof MainFinanceIncomeRoute
  '/leads/archive': typeof MainLeadsArchiveRoute
  '/leads/sources': typeof MainLeadsSourcesRoute
  '/settings': typeof MainSettingsMainIndexRoute
  '/finance': typeof MainFinanceIndexRoute
  '/groups': typeof MainGroupsIndexRoute
  '/leads': typeof MainLeadsIndexRoute
  '/students': typeof MainStudentsIndexRoute
  '/attendance/employees': typeof MainAttendanceMainEmployeesRoute
  '/attendance/students': typeof MainAttendanceMainStudentsRoute
  '/employees/hr': typeof MainEmployeesMainHrRoute
  '/employees/salary': typeof MainEmployeesMainSalaryRoute
  '/groups/$id': typeof MainGroupsIdMainIndexRoute
  '/leads/forms/$id': typeof MainLeadsFormsIdRoute
  '/leads/forms/create': typeof MainLeadsFormsCreateRoute
  '/settings/branches': typeof MainSettingsMainBranchesRoute
  '/settings/courses': typeof MainSettingsMainCoursesRoute
  '/settings/holidays': typeof MainSettingsMainHolidaysRoute
  '/settings/payment-type': typeof MainSettingsMainPaymentTypeRoute
  '/settings/roles': typeof MainSettingsMainRolesRoute
  '/settings/rooms': typeof MainSettingsMainRoomsRoute
  '/students/$id': typeof MainStudentsIdMainRouteWithChildren
  '/employees/attendance': typeof MainEmployeesMainAttendanceLazyRoute
  '/leads/$id': typeof MainLeadsIdIndexRoute
  '/leads/forms': typeof MainLeadsFormsIndexRoute
  '/leads/stats': typeof MainLeadsStatsIndexRoute
  '/groups/$id/attendance': typeof MainGroupsIdMainAttendanceRoute
  '/groups/$id/notes': typeof MainGroupsIdMainNotesRoute
  '/groups/$id/sale': typeof MainGroupsIdMainSaleRoute
  '/groups/$id/score': typeof MainGroupsIdMainScoreRoute
  '/groups/$id/students': typeof MainGroupsIdMainStudentsRoute
  '/leads/$id/user/$user': typeof MainLeadsIdUserUserRoute
  '/leads/forms/edit/$id': typeof MainLeadsFormsEditIdRoute
  '/students/$id/appropriation': typeof MainStudentsIdMainAppropriationRoute
  '/students/$id/discount': typeof MainStudentsIdMainDiscountRoute
  '/students/$id/groups': typeof MainStudentsIdMainGroupsRoute
  '/students/$id/history': typeof MainStudentsIdMainHistoryRoute
  '/students/$id/notes': typeof MainStudentsIdMainNotesRoute
  '/students/$id/parents': typeof MainStudentsIdMainParentsRoute
  '/students/$id/payments': typeof MainStudentsIdMainPaymentsRoute
  '/students/$id/send-message': typeof MainStudentsIdMainSendMessageRoute
  '/groups/$id/tasks': typeof MainGroupsIdMainTasksIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_main/reports': typeof MainReportsRoute
  '/form/$id': typeof FormIdRoute
  '/_auth/login': typeof AuthLoginLazyRoute
  '/_main/': typeof MainIndexRoute
  '/_main/attendance': typeof MainAttendanceRouteWithChildren
  '/_main/attendance/_main': typeof MainAttendanceMainRouteWithChildren
  '/_main/employees': typeof MainEmployeesRouteWithChildren
  '/_main/employees/_main': typeof MainEmployeesMainRouteWithChildren
  '/_main/finance/cost': typeof MainFinanceCostRoute
  '/_main/finance/income': typeof MainFinanceIncomeRoute
  '/_main/leads/archive': typeof MainLeadsArchiveRoute
  '/_main/leads/sources': typeof MainLeadsSourcesRoute
  '/_main/settings': typeof MainSettingsRouteWithChildren
  '/_main/settings/_main': typeof MainSettingsMainRouteWithChildren
  '/_main/finance/': typeof MainFinanceIndexRoute
  '/_main/groups/': typeof MainGroupsIndexRoute
  '/_main/leads/': typeof MainLeadsIndexRoute
  '/_main/students/': typeof MainStudentsIndexRoute
  '/_main/attendance/_main/employees': typeof MainAttendanceMainEmployeesRoute
  '/_main/attendance/_main/students': typeof MainAttendanceMainStudentsRoute
  '/_main/employees/_main/hr': typeof MainEmployeesMainHrRoute
  '/_main/employees/_main/salary': typeof MainEmployeesMainSalaryRoute
  '/_main/groups/$id': typeof MainGroupsIdRouteWithChildren
  '/_main/groups/$id/_main': typeof MainGroupsIdMainRouteWithChildren
  '/_main/leads/forms/$id': typeof MainLeadsFormsIdRoute
  '/_main/leads/forms/create': typeof MainLeadsFormsCreateRoute
  '/_main/settings/_main/branches': typeof MainSettingsMainBranchesRoute
  '/_main/settings/_main/courses': typeof MainSettingsMainCoursesRoute
  '/_main/settings/_main/holidays': typeof MainSettingsMainHolidaysRoute
  '/_main/settings/_main/payment-type': typeof MainSettingsMainPaymentTypeRoute
  '/_main/settings/_main/roles': typeof MainSettingsMainRolesRoute
  '/_main/settings/_main/rooms': typeof MainSettingsMainRoomsRoute
  '/_main/students/$id': typeof MainStudentsIdRouteWithChildren
  '/_main/students/$id/_main': typeof MainStudentsIdMainRouteWithChildren
  '/_main/employees/_main/attendance': typeof MainEmployeesMainAttendanceLazyRoute
  '/_main/attendance/_main/': typeof MainAttendanceMainIndexRoute
  '/_main/employees/_main/': typeof MainEmployeesMainIndexRoute
  '/_main/leads/$id/': typeof MainLeadsIdIndexRoute
  '/_main/leads/forms/': typeof MainLeadsFormsIndexRoute
  '/_main/leads/stats/': typeof MainLeadsStatsIndexRoute
  '/_main/settings/_main/': typeof MainSettingsMainIndexRoute
  '/_main/groups/$id/_main/attendance': typeof MainGroupsIdMainAttendanceRoute
  '/_main/groups/$id/_main/notes': typeof MainGroupsIdMainNotesRoute
  '/_main/groups/$id/_main/sale': typeof MainGroupsIdMainSaleRoute
  '/_main/groups/$id/_main/score': typeof MainGroupsIdMainScoreRoute
  '/_main/groups/$id/_main/students': typeof MainGroupsIdMainStudentsRoute
  '/_main/leads/$id/user/$user': typeof MainLeadsIdUserUserRoute
  '/_main/leads/forms/edit/$id': typeof MainLeadsFormsEditIdRoute
  '/_main/students/$id/_main/appropriation': typeof MainStudentsIdMainAppropriationRoute
  '/_main/students/$id/_main/discount': typeof MainStudentsIdMainDiscountRoute
  '/_main/students/$id/_main/groups': typeof MainStudentsIdMainGroupsRoute
  '/_main/students/$id/_main/history': typeof MainStudentsIdMainHistoryRoute
  '/_main/students/$id/_main/notes': typeof MainStudentsIdMainNotesRoute
  '/_main/students/$id/_main/parents': typeof MainStudentsIdMainParentsRoute
  '/_main/students/$id/_main/payments': typeof MainStudentsIdMainPaymentsRoute
  '/_main/students/$id/_main/send-message': typeof MainStudentsIdMainSendMessageRoute
  '/_main/groups/$id/_main/': typeof MainGroupsIdMainIndexRoute
  '/_main/groups/$id/_main/tasks/': typeof MainGroupsIdMainTasksIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/reports'
    | '/form/$id'
    | '/login'
    | '/'
    | '/attendance'
    | '/employees'
    | '/finance/cost'
    | '/finance/income'
    | '/leads/archive'
    | '/leads/sources'
    | '/settings'
    | '/finance'
    | '/groups'
    | '/leads'
    | '/students'
    | '/attendance/employees'
    | '/attendance/students'
    | '/employees/hr'
    | '/employees/salary'
    | '/groups/$id'
    | '/leads/forms/$id'
    | '/leads/forms/create'
    | '/settings/branches'
    | '/settings/courses'
    | '/settings/holidays'
    | '/settings/payment-type'
    | '/settings/roles'
    | '/settings/rooms'
    | '/students/$id'
    | '/employees/attendance'
    | '/attendance/'
    | '/employees/'
    | '/leads/$id'
    | '/leads/forms'
    | '/leads/stats'
    | '/settings/'
    | '/groups/$id/attendance'
    | '/groups/$id/notes'
    | '/groups/$id/sale'
    | '/groups/$id/score'
    | '/groups/$id/students'
    | '/leads/$id/user/$user'
    | '/leads/forms/edit/$id'
    | '/students/$id/appropriation'
    | '/students/$id/discount'
    | '/students/$id/groups'
    | '/students/$id/history'
    | '/students/$id/notes'
    | '/students/$id/parents'
    | '/students/$id/payments'
    | '/students/$id/send-message'
    | '/groups/$id/'
    | '/groups/$id/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/reports'
    | '/form/$id'
    | '/login'
    | '/'
    | '/attendance'
    | '/employees'
    | '/finance/cost'
    | '/finance/income'
    | '/leads/archive'
    | '/leads/sources'
    | '/settings'
    | '/finance'
    | '/groups'
    | '/leads'
    | '/students'
    | '/attendance/employees'
    | '/attendance/students'
    | '/employees/hr'
    | '/employees/salary'
    | '/groups/$id'
    | '/leads/forms/$id'
    | '/leads/forms/create'
    | '/settings/branches'
    | '/settings/courses'
    | '/settings/holidays'
    | '/settings/payment-type'
    | '/settings/roles'
    | '/settings/rooms'
    | '/students/$id'
    | '/employees/attendance'
    | '/leads/$id'
    | '/leads/forms'
    | '/leads/stats'
    | '/groups/$id/attendance'
    | '/groups/$id/notes'
    | '/groups/$id/sale'
    | '/groups/$id/score'
    | '/groups/$id/students'
    | '/leads/$id/user/$user'
    | '/leads/forms/edit/$id'
    | '/students/$id/appropriation'
    | '/students/$id/discount'
    | '/students/$id/groups'
    | '/students/$id/history'
    | '/students/$id/notes'
    | '/students/$id/parents'
    | '/students/$id/payments'
    | '/students/$id/send-message'
    | '/groups/$id/tasks'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_main/reports'
    | '/form/$id'
    | '/_auth/login'
    | '/_main/'
    | '/_main/attendance'
    | '/_main/attendance/_main'
    | '/_main/employees'
    | '/_main/employees/_main'
    | '/_main/finance/cost'
    | '/_main/finance/income'
    | '/_main/leads/archive'
    | '/_main/leads/sources'
    | '/_main/settings'
    | '/_main/settings/_main'
    | '/_main/finance/'
    | '/_main/groups/'
    | '/_main/leads/'
    | '/_main/students/'
    | '/_main/attendance/_main/employees'
    | '/_main/attendance/_main/students'
    | '/_main/employees/_main/hr'
    | '/_main/employees/_main/salary'
    | '/_main/groups/$id'
    | '/_main/groups/$id/_main'
    | '/_main/leads/forms/$id'
    | '/_main/leads/forms/create'
    | '/_main/settings/_main/branches'
    | '/_main/settings/_main/courses'
    | '/_main/settings/_main/holidays'
    | '/_main/settings/_main/payment-type'
    | '/_main/settings/_main/roles'
    | '/_main/settings/_main/rooms'
    | '/_main/students/$id'
    | '/_main/students/$id/_main'
    | '/_main/employees/_main/attendance'
    | '/_main/attendance/_main/'
    | '/_main/employees/_main/'
    | '/_main/leads/$id/'
    | '/_main/leads/forms/'
    | '/_main/leads/stats/'
    | '/_main/settings/_main/'
    | '/_main/groups/$id/_main/attendance'
    | '/_main/groups/$id/_main/notes'
    | '/_main/groups/$id/_main/sale'
    | '/_main/groups/$id/_main/score'
    | '/_main/groups/$id/_main/students'
    | '/_main/leads/$id/user/$user'
    | '/_main/leads/forms/edit/$id'
    | '/_main/students/$id/_main/appropriation'
    | '/_main/students/$id/_main/discount'
    | '/_main/students/$id/_main/groups'
    | '/_main/students/$id/_main/history'
    | '/_main/students/$id/_main/notes'
    | '/_main/students/$id/_main/parents'
    | '/_main/students/$id/_main/payments'
    | '/_main/students/$id/_main/send-message'
    | '/_main/groups/$id/_main/'
    | '/_main/groups/$id/_main/tasks/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
  FormIdRoute: typeof FormIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
  FormIdRoute: FormIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_main",
        "/form/$id"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/login"
      ]
    },
    "/_main": {
      "filePath": "_main.tsx",
      "children": [
        "/_main/reports",
        "/_main/",
        "/_main/attendance",
        "/_main/employees",
        "/_main/finance/cost",
        "/_main/finance/income",
        "/_main/leads/archive",
        "/_main/leads/sources",
        "/_main/settings",
        "/_main/finance/",
        "/_main/groups/",
        "/_main/leads/",
        "/_main/students/",
        "/_main/groups/$id",
        "/_main/leads/forms/$id",
        "/_main/leads/forms/create",
        "/_main/students/$id",
        "/_main/leads/$id/",
        "/_main/leads/forms/",
        "/_main/leads/stats/",
        "/_main/leads/$id/user/$user",
        "/_main/leads/forms/edit/$id"
      ]
    },
    "/_main/reports": {
      "filePath": "_main/reports.tsx",
      "parent": "/_main"
    },
    "/form/$id": {
      "filePath": "form/$id.tsx"
    },
    "/_auth/login": {
      "filePath": "_auth/login.lazy.tsx",
      "parent": "/_auth"
    },
    "/_main/": {
      "filePath": "_main/index.tsx",
      "parent": "/_main"
    },
    "/_main/attendance": {
      "filePath": "_main/attendance",
      "parent": "/_main",
      "children": [
        "/_main/attendance/_main"
      ]
    },
    "/_main/attendance/_main": {
      "filePath": "_main/attendance/_main.tsx",
      "parent": "/_main/attendance",
      "children": [
        "/_main/attendance/_main/employees",
        "/_main/attendance/_main/students",
        "/_main/attendance/_main/"
      ]
    },
    "/_main/employees": {
      "filePath": "_main/employees",
      "parent": "/_main",
      "children": [
        "/_main/employees/_main"
      ]
    },
    "/_main/employees/_main": {
      "filePath": "_main/employees/_main.tsx",
      "parent": "/_main/employees",
      "children": [
        "/_main/employees/_main/hr",
        "/_main/employees/_main/salary",
        "/_main/employees/_main/attendance",
        "/_main/employees/_main/"
      ]
    },
    "/_main/finance/cost": {
      "filePath": "_main/finance/cost.tsx",
      "parent": "/_main"
    },
    "/_main/finance/income": {
      "filePath": "_main/finance/income.tsx",
      "parent": "/_main"
    },
    "/_main/leads/archive": {
      "filePath": "_main/leads/archive.tsx",
      "parent": "/_main"
    },
    "/_main/leads/sources": {
      "filePath": "_main/leads/sources.tsx",
      "parent": "/_main"
    },
    "/_main/settings": {
      "filePath": "_main/settings",
      "parent": "/_main",
      "children": [
        "/_main/settings/_main"
      ]
    },
    "/_main/settings/_main": {
      "filePath": "_main/settings/_main.tsx",
      "parent": "/_main/settings",
      "children": [
        "/_main/settings/_main/branches",
        "/_main/settings/_main/courses",
        "/_main/settings/_main/holidays",
        "/_main/settings/_main/payment-type",
        "/_main/settings/_main/roles",
        "/_main/settings/_main/rooms",
        "/_main/settings/_main/"
      ]
    },
    "/_main/finance/": {
      "filePath": "_main/finance/index.tsx",
      "parent": "/_main"
    },
    "/_main/groups/": {
      "filePath": "_main/groups/index.tsx",
      "parent": "/_main"
    },
    "/_main/leads/": {
      "filePath": "_main/leads/index.tsx",
      "parent": "/_main"
    },
    "/_main/students/": {
      "filePath": "_main/students/index.tsx",
      "parent": "/_main"
    },
    "/_main/attendance/_main/employees": {
      "filePath": "_main/attendance/_main/employees.tsx",
      "parent": "/_main/attendance/_main"
    },
    "/_main/attendance/_main/students": {
      "filePath": "_main/attendance/_main/students.tsx",
      "parent": "/_main/attendance/_main"
    },
    "/_main/employees/_main/hr": {
      "filePath": "_main/employees/_main/hr.tsx",
      "parent": "/_main/employees/_main"
    },
    "/_main/employees/_main/salary": {
      "filePath": "_main/employees/_main/salary.tsx",
      "parent": "/_main/employees/_main"
    },
    "/_main/groups/$id": {
      "filePath": "_main/groups/$id",
      "parent": "/_main",
      "children": [
        "/_main/groups/$id/_main"
      ]
    },
    "/_main/groups/$id/_main": {
      "filePath": "_main/groups/$id/_main.tsx",
      "parent": "/_main/groups/$id",
      "children": [
        "/_main/groups/$id/_main/attendance",
        "/_main/groups/$id/_main/notes",
        "/_main/groups/$id/_main/sale",
        "/_main/groups/$id/_main/score",
        "/_main/groups/$id/_main/students",
        "/_main/groups/$id/_main/",
        "/_main/groups/$id/_main/tasks/"
      ]
    },
    "/_main/leads/forms/$id": {
      "filePath": "_main/leads/forms/$id.tsx",
      "parent": "/_main"
    },
    "/_main/leads/forms/create": {
      "filePath": "_main/leads/forms/create.tsx",
      "parent": "/_main"
    },
    "/_main/settings/_main/branches": {
      "filePath": "_main/settings/_main/branches.tsx",
      "parent": "/_main/settings/_main"
    },
    "/_main/settings/_main/courses": {
      "filePath": "_main/settings/_main/courses.tsx",
      "parent": "/_main/settings/_main"
    },
    "/_main/settings/_main/holidays": {
      "filePath": "_main/settings/_main/holidays.tsx",
      "parent": "/_main/settings/_main"
    },
    "/_main/settings/_main/payment-type": {
      "filePath": "_main/settings/_main/payment-type.tsx",
      "parent": "/_main/settings/_main"
    },
    "/_main/settings/_main/roles": {
      "filePath": "_main/settings/_main/roles.tsx",
      "parent": "/_main/settings/_main"
    },
    "/_main/settings/_main/rooms": {
      "filePath": "_main/settings/_main/rooms.tsx",
      "parent": "/_main/settings/_main"
    },
    "/_main/students/$id": {
      "filePath": "_main/students/$id",
      "parent": "/_main",
      "children": [
        "/_main/students/$id/_main"
      ]
    },
    "/_main/students/$id/_main": {
      "filePath": "_main/students/$id/_main.tsx",
      "parent": "/_main/students/$id",
      "children": [
        "/_main/students/$id/_main/appropriation",
        "/_main/students/$id/_main/discount",
        "/_main/students/$id/_main/groups",
        "/_main/students/$id/_main/history",
        "/_main/students/$id/_main/notes",
        "/_main/students/$id/_main/parents",
        "/_main/students/$id/_main/payments",
        "/_main/students/$id/_main/send-message"
      ]
    },
    "/_main/employees/_main/attendance": {
      "filePath": "_main/employees/_main/attendance.lazy.tsx",
      "parent": "/_main/employees/_main"
    },
    "/_main/attendance/_main/": {
      "filePath": "_main/attendance/_main/index.tsx",
      "parent": "/_main/attendance/_main"
    },
    "/_main/employees/_main/": {
      "filePath": "_main/employees/_main/index.tsx",
      "parent": "/_main/employees/_main"
    },
    "/_main/leads/$id/": {
      "filePath": "_main/leads/$id/index.tsx",
      "parent": "/_main"
    },
    "/_main/leads/forms/": {
      "filePath": "_main/leads/forms/index.tsx",
      "parent": "/_main"
    },
    "/_main/leads/stats/": {
      "filePath": "_main/leads/stats/index.tsx",
      "parent": "/_main"
    },
    "/_main/settings/_main/": {
      "filePath": "_main/settings/_main/index.tsx",
      "parent": "/_main/settings/_main"
    },
    "/_main/groups/$id/_main/attendance": {
      "filePath": "_main/groups/$id/_main/attendance.tsx",
      "parent": "/_main/groups/$id/_main"
    },
    "/_main/groups/$id/_main/notes": {
      "filePath": "_main/groups/$id/_main/notes.tsx",
      "parent": "/_main/groups/$id/_main"
    },
    "/_main/groups/$id/_main/sale": {
      "filePath": "_main/groups/$id/_main/sale.tsx",
      "parent": "/_main/groups/$id/_main"
    },
    "/_main/groups/$id/_main/score": {
      "filePath": "_main/groups/$id/_main/score.tsx",
      "parent": "/_main/groups/$id/_main"
    },
    "/_main/groups/$id/_main/students": {
      "filePath": "_main/groups/$id/_main/students.tsx",
      "parent": "/_main/groups/$id/_main"
    },
    "/_main/leads/$id/user/$user": {
      "filePath": "_main/leads/$id/user/$user.tsx",
      "parent": "/_main"
    },
    "/_main/leads/forms/edit/$id": {
      "filePath": "_main/leads/forms/edit/$id.tsx",
      "parent": "/_main"
    },
    "/_main/students/$id/_main/appropriation": {
      "filePath": "_main/students/$id/_main/appropriation.tsx",
      "parent": "/_main/students/$id/_main"
    },
    "/_main/students/$id/_main/discount": {
      "filePath": "_main/students/$id/_main/discount.tsx",
      "parent": "/_main/students/$id/_main"
    },
    "/_main/students/$id/_main/groups": {
      "filePath": "_main/students/$id/_main/groups.tsx",
      "parent": "/_main/students/$id/_main"
    },
    "/_main/students/$id/_main/history": {
      "filePath": "_main/students/$id/_main/history.tsx",
      "parent": "/_main/students/$id/_main"
    },
    "/_main/students/$id/_main/notes": {
      "filePath": "_main/students/$id/_main/notes.tsx",
      "parent": "/_main/students/$id/_main"
    },
    "/_main/students/$id/_main/parents": {
      "filePath": "_main/students/$id/_main/parents.tsx",
      "parent": "/_main/students/$id/_main"
    },
    "/_main/students/$id/_main/payments": {
      "filePath": "_main/students/$id/_main/payments.tsx",
      "parent": "/_main/students/$id/_main"
    },
    "/_main/students/$id/_main/send-message": {
      "filePath": "_main/students/$id/_main/send-message.tsx",
      "parent": "/_main/students/$id/_main"
    },
    "/_main/groups/$id/_main/": {
      "filePath": "_main/groups/$id/_main/index.tsx",
      "parent": "/_main/groups/$id/_main"
    },
    "/_main/groups/$id/_main/tasks/": {
      "filePath": "_main/groups/$id/_main/tasks/index.tsx",
      "parent": "/_main/groups/$id/_main"
    }
  }
}
ROUTE_MANIFEST_END */
