name: Deploy Vite React App

on:
    push:
        branches:
            - prod

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            # 1. Checkout code
            - name: Checkout code
              uses: actions/checkout@v4

            # 2. Setup Node.js
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: "pnpm"

            # 3. Setup pnpm (rasmiy action)
            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9.14.4 # sizning loyihangizdagi pnpm versiyasi

            # 4. Install dependencies
            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            # 5. Build project
            - name: Build project
              run: pnpm build

            # 6. Deploy to server
            - name: Deploy to server
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  HOST: ${{ secrets.HOST }}
                  USERNAME: ${{ secrets.USERNAME }}
              run: |
                  # Create .ssh directory
                  mkdir -p ~/.ssh

                  # Add SSH private key
                  echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa

                  # Disable strict host key checking
                  echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

                  # Sync only contents of dist/ into target folder
                  rsync -avz --delete dist/ $USERNAME@$HOST:/var/www/edu-front/
